export const soilMixGuide = {
  id: 'rooted-with-gibre-soil-mix-guide',
  title: 'Rooted with Gibre Houseplant Soil Mix Guide',
  version: 'v2.0',
  category: 'Soil Mixes',
  description: 'Organize mixes by root preference rather than plant name.',
  lastUpdated: '2026-07-14',
  icon: '🌿',
  type: 'soil-mix-guide',
  intro: 'Organize mixes by root preference rather than plant name.',
  sections: [
    {
      id: 'soil-recipes',
      title: 'Soil Mix Recipes',
      recipes: [
        {
          id: 'base-mix',
          name: 'Base Mix',
          category: 'Tropical',
          description: 'General tropical houseplants',
          bestFor: ['Dracaena', 'Bird of Paradise', 'Fiddle Leaf Fig', 'Tradescantia', 'Pilea', 'Aglaonema'],
          ingredients: ['4 parts Potting Soil', '1 part Perlite', '1/2 part Worm Castings'],
          characteristics: ['Moderate drainage', 'Holds moisture well', 'Good for larger plants'],
        },
        {
          id: 'chunky-aroid-mix',
          name: 'Chunky Aroid Mix',
          category: 'Aroid',
          description: 'Philodendrons, Monsteras, Pothos, and Scindapsus',
          bestFor: ['Monstera', 'Philodendron', 'Birkin', 'Prince of Orange', 'Gloriosum Zebra', 'Micans', 'Pothos', 'Scindapsus', 'Syngonium'],
          ingredients: ['2 parts Potting Soil', '2 parts Orchid Bark', '1 part Perlite', '1/2 part Worm Castings'],
          characteristics: ['Excellent airflow', 'Fast draining', 'Supports aerial roots'],
        },
        {
          id: 'anthurium-mix',
          name: 'Anthurium Mix',
          category: 'Anthurium',
          description: 'Collector Anthuriums',
          bestFor: ['Queen of Hearts', 'Ace of Spades', 'Cuprea', 'Pallidiflorum', 'Other Anthuriums'],
          ingredients: ['2 parts Orchid Bark', '1 part Potting Soil', '1 part Perlite', '1/2 part Coco Coir', '1/2 part Worm Castings'],
          characteristics: ['Very airy', 'Slight moisture retention'],
        },
        {
          id: 'alocasia-mix',
          name: 'Alocasia Mix',
          category: 'Alocasia',
          description: 'All Alocasias',
          bestFor: ['Dragon Scale', 'Frydek', 'Blizzard', 'Black Velvet', 'Venom', 'Scalprum'],
          ingredients: ['2 parts Potting Soil', '2 parts Orchid Bark', '2 parts Perlite', '1 part Coco Coir', '1/2 part Worm Castings'],
          characteristics: ['Airy', 'Moist but never soggy', 'Great for corms'],
        },
        {
          id: 'moisture-mix',
          name: 'Moisture Mix',
          category: 'Moisture Loving',
          description: 'Moisture lovers',
          bestFor: ['Peace Lily', 'Calathea', 'Fittonia', 'Maranta'],
          ingredients: ['4 parts Potting Soil', '1 part Coco Coir', '1 part Perlite', '1/2 part Worm Castings'],
          characteristics: ['Even moisture', 'Good drainage'],
        },
        {
          id: 'african-violet-mix',
          name: 'African Violet Mix',
          category: 'Moisture Loving',
          bestFor: ['African Violet'],
          ingredients: ['3 parts Potting Soil', '2 parts Perlite', '1 part Coco Coir', '1/2 part Worm Castings'],
          characteristics: ['Fine texture', 'Ideal for bottom watering'],
        },
        {
          id: 'lipstick-plant-mix',
          name: 'Lipstick Plant Mix',
          category: 'Aroid',
          bestFor: ['Aeschynanthus', 'Lipstick Plant'],
          ingredients: ['2 parts Potting Soil', '2 parts Orchid Bark', '1 part Perlite', '1/2 part Coco Coir', '1/2 part Worm Castings'],
          characteristics: ['Epiphytic', 'Fast draining'],
        },
        {
          id: 'dry-mix',
          name: 'Dry Mix',
          category: 'Succulent',
          description: 'Succulents and drought-tolerant plants',
          bestFor: ['Haworthia', 'Aloe', 'Snake Plant', 'ZZ', 'String of Hearts'],
          ingredients: ['2 parts Potting Soil', '3 parts Perlite', '2 parts Orchid Bark', '1/2 part Worm Castings, optional'],
          characteristics: ['Very fast draining'],
        },
        {
          id: 'christmas-cactus-mix',
          name: 'Christmas Cactus Mix',
          category: 'Succulent',
          description: 'Holiday cacti',
          bestFor: ['Christmas Cactus', 'Thanksgiving Cactus'],
          ingredients: ['3 parts Potting Soil', '2 parts Orchid Bark', '2 parts Perlite', '1 part Coco Coir', '1/2 part Worm Castings'],
          characteristics: ['Balanced moisture and airflow'],
        },
        {
          id: 'jewel-orchid-mix',
          name: 'Jewel Orchid Mix',
          category: 'Moisture Loving',
          bestFor: ['Ludisia', 'Macodes', 'Anoectochilus', 'Other Jewel Orchids'],
          ingredients: ['2 parts Potting Soil', '1 part Orchid Bark', '1 part Perlite', '1 part Coco Coir', '1/2 part Worm Castings'],
          characteristics: ['Evenly moist', 'Light and airy', 'Rich in organic matter', 'Never completely dries out'],
        },
        {
          id: 'tc-propagation-mix',
          name: 'TC / Propagation Mix',
          category: 'Propagation',
          bestFor: ['Tissue Cultures', 'Corms', 'Fresh Props', 'Rehab plants'],
          ingredients: ['1 part Fluval Stratum', '1 part Perlite'],
          characteristics: ['Sterile', 'Excellent rooting'],
        },
        {
          id: 'semi-hydro',
          name: 'Semi-Hydro',
          category: 'Semi-Hydro',
          medium: 'LECA',
          reservoir: 'About 1/3 of the inner pot',
          instructions: 'Use a weak nutrient solution with each refill.',
        },
      ],
    },
    {
      id: 'optional-additives',
      title: 'Optional Additives',
      notes: [
        { label: 'Worm Castings', text: 'Use on most mature plants.' },
        { label: 'Coco Coir', text: 'Increase for drier homes; reduce if mixes stay wet.' },
        { label: 'Fluval', text: 'Best for tissue cultures, corms, rehab, and rooting.' },
        { label: 'LECA', text: 'Use for semi-hydro only.' },
        { label: 'Phantom Moss', text: 'Best for moss poles, top dressing, and humidity chambers.' },
      ],
    },
    {
      id: 'initial-repotting-philosophy',
      title: 'Initial Repotting Philosophy',
      bullets: [
        'Keep as much of the root ball intact as practical.',
        'Replace poor nursery media rather than removing healthy roots.',
        'Transition plants gradually into chunkier mixes.',
      ],
    },
    {
      id: 'root-disturbance-guide',
      title: 'Root Disturbance Guide',
      notes: [
        { label: 'Anthurium', text: 'Moderate' },
        { label: 'Philodendron, Monstera, and Lipstick Plant', text: 'Light' },
        { label: 'Alocasia', text: 'Minimal' },
        { label: 'African Violet', text: 'High' },
        { label: 'Haworthia and Succulents', text: 'High' },
      ],
    },
  ],
};
